[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "clogs"
version = "1.0.0"
authors = [
  { name="UlifSystems", email="ulifsystems@gmail.com" },
]
description = "A library for creating changelog programmatically with ease."
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
"Homepage" = "https://github.com/ulifprojects/clogs"
"Bug Tracker" = "https://github.com/ulifprojects/clogs/issues"